### ISSUE TITLE
Error installing coreEnv on Ubuntu 16.

### ISSUE THREAD

**Issue by wpoosanguansit** [luke-clifton/nix-config#1]
building path(s) ‘/nix/store/0fz2gah42mzw7zd61rzdsx5rzik4m5pp-coreEnv’
created 354 symlinks in user environment
building path(s) ‘/nix/store/lfzpbi0xrxky6kl74pclq6hydzrlmj9k-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/hrws54iz93a1xbknjpvwk0c4qfkqabwn-git-2.12.2/bin/git’ and ‘/nix/store/0fz2gah42mzw7zd61rzdsx5rzik4m5pp-coreEnv/bin/git’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/j8s9brrmgwccigdhln2shjwv51dsm9b0-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/j8s9brrmgwccigdhln2shjwv51dsm9b0-user-environment.drv’ failed

However, installing baseEnv seems to be fine without any error.

But baseXEnv would fail:

Hunk #1 succeeded at 135 with fuzz 1 (offset 44 lines).
Hunk #2 FAILED at 184.
Hunk #3 FAILED at 844.
Hunk #4 succeeded at 1467 with fuzz 1 (offset 289 lines).
2 out of 4 hunks FAILED -- saving rejects to file surf.c.rej
builder for ‘/nix/store/zp49grd63jdsxrn52lhraffzkil84h39-surf-2.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/2vx6pm4xi8vsfiwgyy3n62zfsp626j89-baseXEnv.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/2vx6pm4xi8vsfiwgyy3n62zfsp626j89-baseXEnv.drv’ failed

**Comment by luke-clifton** [comment]
This is just because you already have git installed.
